### ISSUE TITLE
Error when running "yo wet-boew-theme" generator

### ISSUE THREAD

**Issue by gvautour** [wet-boew/wet-boew#8270]
I'm having significant issues setting up the wet-boew-theme generator on Windows.

"yo wet-boew-theme" failed on "npm install".

After running the command "npm install" manually I'm getting the following errors:

C:\Development\GaC\G7Web>npm i
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> node-sass@0.9.3 install C:\Development\GaC\G7Web\node_modules\node-sass
> node build.js

(node:11896) [DEP0006] DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.

C:\Development\GaC\G7Web\node_modules\node-sass>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Development\GaC\G7Web\node_modules\node-sass\build\bi
nding.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Development\GaC\G7Web\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed
npm WARN g7web@4.0.21 No description
npm WARN g7web@4.0.21 No repository field.

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2018-01-26T14_36_23_204Z-debug.log

C:\Development\GaC\G7Web>

**Comment by duboisp** [comment]
@gvautour I think you may need an old version of node to run the theme generator. You can have multiple version of node by using a node manager like nvm or something equivalent.

As an interim solution, you can use an existing theme, like GCweb or wet-boew theme and then overwrite its CSS rules to obtain your design.

**Comment by RobJohnston** [comment]
This should probably be in the generator-wet-boew-theme repo.  See also https://github.com/wet-boew/generator-wet-boew-theme/issues/35.

**Comment by StdGit** [comment]
Do we still need wget:jqueryOldIE

With node v10.16.3, it breaks the build

```
`	@registerTask(
		"init"
		"Only needed when the repo is first cloned"
		[
#			"modernizr"
			"wget:jqueryOldIE"
		]
)`
```
