### ISSUE TITLE
Running "yo wet-boew-theme" results in error "primordials is not defined"

### ISSUE THREAD

**Issue by auroris** [wet-boew/wet-boew#8802]
I followed the instructions given on "I want to customize WET and design a new WET theme" on the [Getting Started](https://wet-boew.github.io/wet-boew/docs/start-en.html) page. Under both Windows and Linux, an error message similar to the following was produced:
```
ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/usr/lib/node_modules/generator-wet-boew-theme/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/lib/node_modules/generator-wet-boew-theme/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/lib/node_modules/generator-wet-boew-theme/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```
This error message appears to be occurring early enough in the process that no files are produced in the working directory. The node version being used is 12.13 on linux and 12.14 on windows.

**Comment by thekodester** [comment]
The theme generator has been broken since 2017 see https://github.com/wet-boew/generator-wet-boew-theme/issues.

WET changed it focus to only:

Web Experience Toolkit (WET): https://github.com/wet-boew/wet-boew
Canada.ca (GCWeb): https://github.com/wet-boew/GCWeb

And a small number of other repositories (wet-boew-styleguide, wet-boew-documentation, etc).

See https://github.com/wet-boew/wet-boew/issues/8366.

###### I am just a volunteer on this GitHub project.

**Comment by auroris** [comment]
Thanks.
