### ISSUE TITLE
[BUG] Unable to run setup script

### ISSUE THREAD

**Issue by at88mph** [wet-boew/wet-boew#9187]
## Required information

**Describe the bug**
Related to #9155 
I would like to reopen this one please.  The current build script cannot complete as it dies on `SlimerJS` after many deprecation warnings:

```
10770 error npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
10770 error npm ERR! code 1
10770 error npm ERR! path /root/.npm/_cacache/tmp/git-clone-3a2ad4b6/node_modules/slimerjs
10770 error npm ERR! command failed
10770 error npm ERR! command sh -c node install.js
10770 error npm ERR! SlimerJS not found on PATH
10770 error npm ERR! Slimer installation failed TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
10770 error npm ERR!     at validateString (internal/validators.js:120:11)
10770 error npm ERR!     at Object.join (path.js:1039:7)
10770 error npm ERR!     at findSuitableTempDirectory (/root/.npm/_cacache/tmp/git-clone-3a2ad4b6/node_modules/slimerjs/install.js:113:30)
10770 error npm ERR!     at /root/.npm/_cacache/tmp/git-clone-3a2ad4b6/node_modules/slimerjs/install.js:408:19
10770 error npm ERR!     at nextTickCallback (/root/.npm/_cacache/tmp/git-clone-3a2ad4b6/node_modules/kew/kew.js:47:28)
10770 error npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
10770 error npm ERR!   code: 'ERR_INVALID_ARG_TYPE'
10770 error npm ERR! } TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
10770 error npm ERR!     at validateString (internal/validators.js:120:11)
10770 error npm ERR!     at Object.join (path.js:1039:7)
10770 error npm ERR!     at findSuitableTempDirectory (/root/.npm/_cacache/tmp/git-clone-3a2ad4b6/node_modules/slimerjs/install.js:113:30)
10770 error npm ERR!     at /root/.npm/_cacache/tmp/git-clone-3a2ad4b6/node_modules/slimerjs/install.js:408:19
10770 error npm ERR!     at nextTickCallback (/root/.npm/_cacache/tmp/git-clone-3a2ad4b6/node_modules/kew/kew.js:47:28)
10770 error npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:79:11)
10770 error
10770 error npm ERR! A complete log of this run can be found in:
10770 error npm ERR!     /root/.npm/_cacache/_logs/2021-10-01T21_16_49_193Z-debug.log
10771 verbose exit 1
```

This is running with Node 12.2 in Docker (Debian bullseye) with WET 4.0.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to project root
2. Run ./script/setup
3. See error after building some dependencies

**Expected behaviour**
Expected to complete successfully to be able to run Grunt.

**Who shall do the work?**
I am asking for Principal publisher to please do the work

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
4.0.43

**Desktop/Smartphone (please complete the following information)**

**Screenshots**

**Additional context**
 - Needed to modify `script/setup` to use `--legacy-peer-deps` with `npm install`.

**Comment by at88mph** [comment]
I found a way around this.  I was using Debian 11 with NodeJS 12, which appears to be too new.  I downgraded to Debian 10 with NodeJS 10, an that seems to have fixed my issue.
