### ISSUE TITLE
[BUG] Feature name - Short description of the bug

### ISSUE THREAD

**Issue by markbernard** [wet-boew/wet-boew#9370]
## Required information

**Describe the bug**
When trying to dynamically load a script using jQuery getScript the following error is generated:
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at Object.send (jquery.js:9247:19)
    at Function.ajax (jquery.js:8656:15)
    at Function.jQuery.<computed> [as get] (jquery.js:8807:17)
    at Function.getScript (jquery.js:8792:17)
    at HTMLDocument.<anonymous> (cms-widgets.js:91:11)
    at fire (jquery.js:3187:31)
    at Object.fireWith [as resolveWith] (jquery.js:3317:7)
    at Function.ready (jquery.js:3536:13)
    at HTMLDocument.completed (jquery.js:3552:9)

This error has not appeared before until wet-boew.js started overloading jQuery functions. We are currently using version 4.0.38 with no issue. Attempting to upgrade to 4.0.49.1 causes this problem.

Putting a breakpoint at line 9247 in **jquery.js** shows that the **search** variable does not have the correct object value assigned to it. It should be a size one array but there is no array at all.

**To Reproduce**
1. $.getScript("path to any Javascript").done(function() {
                console.log("Success");
            })
            .fail(function( jqxhr, settings, exception ) {
                console.log("Fail");
                console.log(exception);
            });
The error will be thrown.

**Expected behaviour**
The Javascript file should be loaded and executed with no issue.

**Who shall do the work?**
I am asking for Principal publisher to please do the work

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
v4.0.49.1

**Desktop/Smartphone (please complete the following information)**
 - Windows 10 Desktop
 - Browser
   - Chrome Version 101.0.4951.54 (Official Build) (64-bit
   - EDGE Version 101.0.1210.39 (Official build) (64-bit)

**Screenshots**
If applicable, add screenshots to help explain the bug.

**Additional context**

**Comment by duboisp** [comment]
@markbernard this is related to a security fix we applied to jquery for wet-boew last November.

You will need to use an alternative solution to load your script, like with Modernizr which are included in wet-boew. Like how we do in the: [data tables](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L81), [form validation](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/formvalid/formvalid.js#L68), [lightbox](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/lightbox/lightbox.js#L267)...  Feel free to join us during one of our [weekly office hours](https://github.com/wet-boew/wet-boew/wiki/WET-Office-hours,-Heures-de-service-de-la-BOEW) if you need assistance.

**Comment by markbernard** [comment]
Thanks. I found a workaround that is more modern. Go ahead and close this.

**Comment by eeidsness** [comment]
I would suggest changing the name of this issue so it's easier to find.  I came across this issue with the newest release of CDTS.  Took me a while to realize how I can fix it.  

I came across a solution on this page, that worked well for me.
https://aaronsmith.online/easily-load-an-external-script-using-javascript/

first a function
```javascript
const loadScript = src => {
  return new Promise((resolve, reject) => {
    const script = document.createElement('script')
    script.type = 'text/javascript'
    script.onload = resolve
    script.onerror = reject
    script.src = src
    document.head.append(script)
  })
}
```
then implementing
```javascript
loadScript('//js.arcgis.com/4.15/')
  .then(() => {
    // do stuff
  })
  .catch(() => console.error('Something went wrong.'))

```
