### ISSUE TITLE
[BUG] Issue with datatables.net when sorting array

### ISSUE THREAD

**Issue by DBlaisAsc** [wet-boew/wet-boew#9718]
I'm using datatables.net feature, with ajax loading data/objects.  Some properties that I'm loading are array of string.  Datatables.net already handle this without issue and show all values.

But, when I click column header to sort on that column, I got that issue :

Uncaught TypeError: e.split is not a function
    at d.normalizeDiacritics (wet-boew.js:3742:15)
    at string-pre (wet-boew.js:14221:18)
    at ae (jquery.dataTables.min.js:4:44388)
    at Kt (jquery.dataTables.min.js:4:42064)
    at ut (jquery.dataTables.min.js:4:23510)
    at te (jquery.dataTables.min.js:4:43538)
    at jquery.dataTables.min.js:4:43708

The line is : `chars = str.split( "" ),`

The reason is str is an array of string, not an string.

Also, if the source is null, that function is also generating an issue.  I fix that previous issue by adding that validation :

```
            wb.normalizeDiacritics = function (str) {
                if (str === null)  // Fix
                    return null;
```

Regards

**Comment by wewhite** [comment]
What version of wet-boew are you using?
