### ISSUE TITLE
[BUG] Js Error on Reload in Chrome for Tabbed Interface

### ISSUE THREAD

**Issue by TheDuke13** [wet-boew/wet-boew#9773]
## Required information

We seem to be experiencing a new issue on a website we manage where the Tabbed Interface fails to initialize on page reloads. Upon further investigation it seems like a JS error when the page reloads (first load works as expected) that might affect the entire WET-BOEW library. We've replicated the issue on the documentation pages.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [the tabbed interface example page](https://wet-boew.github.io/wet-boew/demos/tabs/tabs-en.html)
2. Notice the tabs are initalized and working
3. Click on reload within the browser
4. See the following error in the Developer Console
```
Uncaught TypeError: Cannot read properties of null (reading 'insertBefore')
    at e.yepnope.injectJs (wet-boew.js:1999:7686)
    at wet-boew.js:1999:4461
```

**Expected behaviour**
When reloading the page the tabs should be initialized.

**Who shall do the work?**
I'm hoping someone on the team can investigate the possible Bug or Browser issue.

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
Issue presented on a site running 4.0.74 but also present when reverted to previous version 4.0.50.1 and also replicated the issue on the current 4.0.80 version from the examples.

**Desktop/Smartphone (please complete the following information)**
 - OS or Device: MacOS and Windows 11
 - Browser Chrome
 - Version 125.0.6422.112

**Screenshots**
Screenshot of initial load:
![Screenshot 2024-05-28 at 1 58 37 PM](https://github.com/wet-boew/wet-boew/assets/2488392/d42d6081-defc-491b-b017-bfa8b31dd569)

Screenshot of reload:
![Screenshot 2024-05-28 at 1 58 30 PM](https://github.com/wet-boew/wet-boew/assets/2488392/459b196f-de20-40ad-a636-6e702c757064)

**Additional context**
We've tested with other Browsers (latest 3 Firefox, latest 3 Safari, latest 3 Edge) and we couldn't get this issue to happen.

**Comment by TheDuke13** [comment]
Further testing revealed that a browser extension was causing conflicts with the WET-BOEW functions on reload
